### ISSUE TITLE
Holes on Geometry

### ISSUE THREAD

**Issue by koiava** [embree/embree#109]
There are noticeable artifacts in Embree examples. It looks like intersection test fails close to triangle edges which are at center of the camera. (Please see images 
![intersection](https://cloud.githubusercontent.com/assets/3224013/21092831/f21ca0f4-c04e-11e6-822f-4839494dd021.png)
![intersection_2](https://cloud.githubusercontent.com/assets/3224013/21092829/f21ba3ca-c04e-11e6-8d9e-dba324e2a94b.png)
)

**Comment by cbenthin** [comment]
The "triangle_geometry" tutorial does not use Embree's robust intersection mode as default mode. If you specify "RTC_SCENE_STATIC | RTC_SCENE_ROBUST" for rtcDeviceNewScene the artifacts should disappear. 

The artifacts in the "displaced_geometry" tutorial seem to be caused by the displacement shader. The related "subdivision_geometry" tutorial without displacements does not show the artifacts. We'll have a closer look at this.
