### ISSUE TITLE
embree on ISA 4.1?

### ISSUE THREAD

**Issue by naturalmechanics** [embree/embree#152]
This is my flags from cat /proc/cpuinfo : 

`fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 lahf_lm dtherm tpr_shadow vnmi flexpriority
`

while parts of embree code does seem to have support for sse4.1, the cmakelist file takes either sse2 or sse4.2 - sse3 or 4.1 can't be used.

 I tested by forcing MAX_ISA to be 2 by exporting MAX_ISA=2 . But the problem is, i need to run OSPray, ISA >= 4.1 How can I build EMBREE with ISA 4.1?

**Comment by cbenthin** [comment]
For your CPU you have to use SSE2 as MAX_ISA for Embree as we don't have a direct SSE41 target. If you compile OSPray separately you should be able to set the ISA for OSPray to sse4.1.

**Comment by naturalmechanics** [comment]
Hi cbenthin
OSPray needs EMBREE compiled against sse4.1. That is the problem

**Comment by johguenther** [comment]
Indeed, but this is only a link-time dependency. You can compile Embree with `MAX_ISA=AVX`, OSPRay will be satisfied, and at runtime only SSE2 is used due to your CPU features.

**Comment by ArchangeGabriel** [comment]
@johguenther To be sure I understand you well: if I compile Embree with say `MAX_ISA=AVX512SKL`, it will work on any computer supporting at least SSE2, but will adapt at runtime to what is available?

**Comment by jeffamstutz** [comment]
Yes, that is correct: Embree will figure out at runtime which internal code paths to use to match the CPU you are running on. The "higher" the value of ```EMBREE_MAX_ISA```, more CPU targets get compiled in. It is additive for Embree (not OSPRay), in that newer ISA support does not remove compatibility for older ISAs at runtime. The shared object version of the library is a "fat binary".

**Comment by jeffamstutz** [comment]
If for any reason this does not work for you, please let us know!

**Comment by ArchangeGabriel** [comment]
Well apparently we (=ArchLinux) package embree as SSE2 because that is the lowest common denominator (and told people to compile themselves if they wanted higher ISA support), but now that I read that I’ll just switch the package to AVX2 (not AVX512SKX nor KNL because of #169).

Then OSPRay will pickup AVX2 as the highest ISA and compile for this, but then will it work for people with only SSE4.1 for instance? I’m not sure on that point because you’ve just implied that it wasn’t additive for OSPRay, yet above @johguenther said that compiling OSPRay with an AVX ISA would be OK for a SSE4.1 max system.

**Comment by ArchangeGabriel** [comment]
That being said, we apparently had a bug when embree got compiled with more than SSE2, https://bugs.archlinux.org/task/51801. We will see whether it surfaces back or not.

**Comment by svenwoop** [comment]
This bug in ISA selection of Embree should be fixed by now.

**Comment by johguenther** [comment]
For OSPRay set/leave `OSPRAY_BUILD_ISA` to `ALL` to get the same behavior as in Embree: support for all ISAs will be compiled in, with run-time detection which ISA eventually to use for the current CPU. What Jeff meant with "different" is that setting `OSPRAY_BUILD_ISA` to a specific ISA will *only* support that ISA, where as in Embree all lower ISA are also supported (because the Embree variable has different semantics, it is consequently called `EMBREE_MAX_ISA`).

**Comment by ArchangeGabriel** [comment]
Thanks a lot to both of you for these information. :) And congrats for having designed you software this way. ;)
