### ISSUE TITLE
Embree 2.17.0 does not compile on VS2015 x64

### ISSUE THREAD

**Issue by florianlink** [embree/embree#157]
I get the following error message:

bvh_builder_sah.cpp.avx.cpp
d:\repository\thirdparty\sources\misc\embree\kernels\builders\bvh_builder_sah.h(140) : fatal error C1063: compiler limit: compiler stack overflow

**Comment by florianlink** [comment]
It only happens in release mode. I placed additional __noinline at various places, but that did not help.

**Comment by cbenthin** [comment]
I guess this is with the Microsoft compiler, right? Have you installed the latest VS updates?

**Comment by florianlink** [comment]
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3

That should be the newest version, right?

**Comment by florianlink** [comment]
I tried various optimizer settings, but it only compiles with disabled optimizer (/Od)

**Comment by cbenthin** [comment]
I could reproduce the issue. That's a nasty internal compiler error. Could you try to enable the EMBREE_STACk_PROTECTOR option in cmake as a workaround. With this it compiles on my machine.

**Comment by florianlink** [comment]
Ok, I can compile it with EMBREE_STACK_PROTECTOR:BOOL=ON

**Comment by cbenthin** [comment]
It seems the enabled stack protection keeps the compiler somehow under the magic 1MB stack limit. I've searched a bit and it seems other people running into this issue with even a lot simpler code. We'll try whether reduced inlining helps to avoid triggering the internal compiler bug, but I fear chances are not really high.

**Comment by florianlink** [comment]
I turned inlining off (in the optimization settings of VC++) and the crash still happened...

**Comment by cbenthin** [comment]
The bug is caused by the new SSA optimizer MS introduced in VS 2015:

https://blogs.msdn.microsoft.com/vcblog/2016/05/04/new-code-optimizer/

By adding -d2SSAOptimizer- to the command line the code compiles fine, however, the code quality might be affected (not tested). Also other people run into this issue before us:

https://bugreports.qt.io/browse/QTBUG-54443?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

As this is an internal MSVC bug and we have two workarounds I'll close the issue for now. If the issue reappears please reopen.

**Comment by demarle** [comment]
Just a note that I ran into this as well. Notes: I was on embree 3.2.0. vs2013 compilation succeeds, vs2017 compilation suceeds, vs2015 compilation failed. EMBREE_STACK_PROTECTOR did not fix it, adding -d2SSAOptimizer- to the CMAKE_CXX_FLAGS did fix it.
