### ISSUE TITLE
Debug build using gcc 4.9.2 spams warnings about problematic global variables, huge executable

### ISSUE THREAD

**Issue by pborsutzki** [embree/embree#170]
I am trying to build a debug version of Embree 2.17.2 using gcc 4.9.2 and TBB 2017_20161128.
My cmake command is this:
`cmake .. -DCMAKE_BUILD_TYPE=Debug -DTBB_INCLUDE_DIR=../../tbb/include -DTBB_LIBRARY=../../tbb/lib/Debug/libtbb_debug.so -DTBB_LIBRARY_MALLOC=../../tbb/lib/Debug/libtbbmalloc_debug.so -DEMBREE_ISPC_SUPPORT=OFF -DEMBREE_TUTORIALS=OFF`
During build I get a lot of warnings with the exact same message (about 50):
```
CMake Warning at /home/pbi1/artifact_builder/embree/embree-2.17.2/common/cmake/check_globals.cmake:28 (message):


  Problematic global variable in non-SSE code:

  0000000000000001 l O .bss     0000000000000001 embree::null
```
Also the resulting binary is 575M big. It works though. 
So should I be worried? Is this intended?

**Comment by svenwoop** [comment]
Nothing to worry about. We will fix this warning in the next release.

**Comment by pborsutzki** [comment]
Ok, thanks!
And what about the executable size? I can't imagine that this is all debug information ...

**Comment by svenwoop** [comment]
Just tried clang, and when compiling with MAX_ISA=AVX2 I get libembree.so of about 300MB. This is probably caused by the compiler not inlining any small functions from the vector classes and the debug symbols. We do not use Debug mode for debugging, but RelWithDebInfo mode, which does optimizations and runs fast, has smaller executable size, contains debug symbols, and asserations.
