### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by elviras9t** [embree/embree#186]
Microsoft planned to support ARM64 in Windows 10, Linux supports ARM64, Android have ARM64... I want to ask question: but Embree will support of ARM64 architectures (included latest NEON's)?

**Comment by cbenthin** [comment]
That's very unlikely to happen as Embree's focus is on x86 ISAs. That said, as Embree is under the Apache license, anyone can modify it the way he likes. Supporting ARM ISAs would mostly involve replacing the x86-based intrinsics layer with their ARM equivalent.

**Comment by qhaas** [comment]
It would be useful if Embree had a 'fallback' to plain ISA agnostic C/C++ code to enable support for other ISAs when x86-64 SIMD support isn't available, even if it were to be horribly slow on ARM, ppc64le, etc.  Otherwise, developers forced to use ARM, ppc64le, etc. for whatever their project needs may be (e.g. embedded for ARM/MIPS, ppc64le for supercomputers), will have to consider other libraries and (likely) contribute their own fixes/enhancements to them, rather than embree.  Having one gold standard for CPU ray-tracing, especially one as liberally licensed as embree, sure makes things easier...

**Comment by aaronfranke** [comment]
@cbenthin Since ARM support has been added, it seems that there is support for non-x86 architectures. Is there any interest in supporting more architectures, such as RISC-V? My guess that there is little interest in this, but is it a case of "we won't work on this but PRs welcome" or "we won't merge this even if someone submits a PR"?
