### ISSUE TITLE
2.4 crashes on Mac Pro with Xeon processors

### ISSUE THREAD

**Issue by ov** [embree/embree#22]
Once again would like to thank you guys for the amazing library!

We're having issues with the recent 2.4 update on Mac Pro with Xeon processors. Embree crashes somewhere in background threads on that computer, but runs just fine on other non-Xeon Macs and PCs.

Replacing 2.4 with 2.3.3 immediately fixes the issue, so I believe something went wrong between these two releases.

The Mac Pro has model number A1186 and has two Intel Xeon 5150 processors. We don't have access to that Mac, as it is our customer's one, so can't do more tests. You have also changed the way debug symbols are stored in 2.4, so Google Breakpad can't parse it anymore, so we don't have a lot of information about the crashes. Here's what we have:

```
Operating system: Mac OS X
                  10.10.1 14B25
CPU: amd64
     family 6 model 15 stepping 11
     8 CPUs

Crash reason:  EXC_BAD_INSTRUCTION / 0x00000001
Crash address: 0x111623639

Thread 25 (crashed)
 0  libembree.2.4.0.dylib + 0x1c6639
    rbx = 0x0b0a0c90   r12 = 0x0b0a0db0   r13 = 0x0b0a0da0   r14 = 0x057763f8
    r15 = 0x0b0a0c90   rip = 0x11623639   rsp = 0x0b09ed70   rbp = 0x0b0a0740
    Found by: given as instruction pointer in context 
```

There are other threads at the same address, so this looks like a worker thread waiting for something. 

If this is not enough, we can provide the application and instructions on reproducing the issue.

Thank you.

**Comment by svenwoop** [comment]
I think I found the problem. We generated one SSE4.1 instruction in the SSE3 version of the code. I fixed the issue in the v2.4 branch and also in the v2.4 binaries for MacOSX. Could you please retry to see if the issue is fixed.

**Comment by ov** [comment]
This may take a few days, but I'll try. Does it affect the Mac binary only?

**Comment by cbenthin** [comment]
Most likely the issue will also affect the Linux binaries. I've just updated them. Would be really great if you could test the Linux binaries as well. Thanks!

**Comment by cbenthin** [comment]
I meant if you have access to a Linux machine supporting the SSE3 ISA only, which I guess are hard to find these days...

**Comment by svenwoop** [comment]
The windows version also had the bug. I just replaced the windows binary.

**Comment by ov** [comment]
Thanks :+1:

**Comment by fluidray** [comment]
We are experiencing a related problem with Embree 2.5.1, built in-house with clang. Our user has a MacPro with Core Xeon X5365. I'm sending him an update including the Embree binary available on  this website to see if that fixes the problem (is it built with the Intel compiler?)

Process:               FluidRay RT (64 Bit) [4586]
Path:                  /Applications/FluidRay RT (64 Bit).app/Contents/MacOS/FluidRay RT (64 Bit)
Identifier:            fluidinteractive.fluidrayrt.pro
Version:               1.1.5 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           FluidRay RT (64 Bit) [4586]
User ID:               501

Date/Time:             2015-06-17 04:57:35.700 -0300
OS Version:            Mac OS X 10.10.4 (14E36b)
Report Version:        11
Anonymous UUID:        F98B6917-0333-90EF-0CD7-1EBE20E82F5B

Sleep/Wake UUID:       B5ED52CB-2B42-4AD7-9FC9-3495BD3D3848

Time Awake Since Boot: 15000 seconds
Time Since Wake:       150 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Application Specific Information:
/Applications/FluidRay RT (64 Bit).app/Contents/Resources/libembree.2.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libembree.2.dylib             0x0000000115c9a329 _GLOBAL__I_a + 25
1   dyld                          	0x00007fff665fbceb ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
2   dyld                          	0x00007fff665fbe78 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
3   dyld                          	0x00007fff665f8871 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305
4   dyld                          	0x00007fff665f8806 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 198
5   dyld                          	0x00007fff665f86f8 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 138
6   dyld                          	0x00007fff665f8969 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
7   dyld                          	0x00007fff665ee063 dyld::runInitializers(ImageLoader*) + 89
8   dyld                          	0x00007fff665f51d1 dlopen + 578
9   libdyld.dylib                 0x00007fff8d0aa857 dlopen + 59
10  fluidinteractive.fluidrayrt.pro	0x000000010c432c0c sys::openLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 300
11  fluidinteractive.fluidrayrt.pro	0x000000010c0c82d7 fluidrayapp::app_manager_t::on_init() + 28455
12  fluidinteractive.fluidrayrt.pro	0x000000010c1406ba FluidRayApp::OnInit() + 42
13  fluidinteractive.fluidrayrt.pro	0x000000010b5612c1 wxApp::CallOnInit() + 65
14  fluidinteractive.fluidrayrt.pro	0x000000010b76b39f wxEntry(int&, wchar_t**) + 47
15  fluidinteractive.fluidrayrt.pro	0x000000010b4580b4 main + 20
16  libdyld.dylib                 0x00007fff8d0ab5c9 start + 1
