### ISSUE TITLE
Ray-point intersection fails when closer than dir length+radius

### ISSUE THREAD

**Issue by UlysseV** [embree/embree#230]
I discovered that when performing ray-point intersections, Embree does not detect  hits when the distance between ray origin and target point is smaller that the point radius+ray dir length.

Here is a minimum working example :
```cpp

#include <embree3/rtcore.h>

int main() {
//--------------------------------
// Initializing Embree
    RTCDevice m_device = rtcNewDevice(nullptr);
    RTCScene m_scene = rtcNewScene(m_device);
    RTCIntersectContext m_context;
    rtcInitIntersectContext(&m_context);

//--------------------------------
// Creating unit sphere geometry
    RTCGeometry m_geometry = rtcNewGeometry(m_device, RTC_GEOMETRY_TYPE_SPHERE_POINT);
    float* point_vertices = (float*)rtcSetNewGeometryBuffer(m_geometry,RTC_BUFFER_TYPE_VERTEX, 0, RTC_FORMAT_FLOAT4, sizeof(float)*4, 1);
    point_vertices[0] = 0.0;
    point_vertices[1] = 0.0;
    point_vertices[2] = 0.0;
    point_vertices[3] = 1.0;
    rtcCommitGeometry(m_geometry);
    uint m_geometryID = rtcAttachGeometry(m_scene, m_geometry);
    rtcReleaseGeometry(m_geometry);
    rtcCommitScene(m_scene);

//--------------------------------
// Forging ray
    float scale = 10.f;
    float org[3] = {scale, 0.f, 0.f};
    float dir[3] = {-1.f, 0.f, 0.f};
    RTCRay ray = {org[0], org[1], org[2], 0.f, dir[0], dir[1], dir[2], 0.5f, std::numeric_limits<float>::infinity(), 0, 0, 0};
    RTCHit hit;
    hit.geomID = RTC_INVALID_GEOMETRY_ID;
    hit.primID = RTC_INVALID_GEOMETRY_ID;
    hit.instID[0] = RTC_INVALID_GEOMETRY_ID;
    RTCRayHit rayHit = {ray, hit};

//--------------------------------
// Casting & analysing ray
    rtcIntersect1(m_scene, &m_context, &rayHit);
    if(rayHit.hit.geomID == m_geometryID)
    {
        std::cout << "Geometry hit ! geomID = " << rayHit.hit.geomID << ", primID = " << rayHit.hit.primID << std::endl;
        std::cout << "Hit point distance : " << rayHit.ray.tfar << std::endl;
        std::cout << "Hit point normal : " << rayHit.hit.Ng_x << ", " << rayHit.hit.Ng_y << ", " << rayHit.hit.Ng_z  << std::endl;
    }
    else
    {
        std::cout << "Geometry missed ! geomID = " << rayHit.hit.geomID << std::endl;
    }

//--------------------------------
// Ending program
    rtcReleaseDevice(m_device);
    return 0;
}
```

When running it with `scale=3`, it displays what is expected :
```
Geometry hit ! geomID = 0, primID = 0
Hit point distance : 3
Hit point normal : 1, 0, 0
```

However, when running the code above with any `scale<2`, the console shows `Geometry missed ! geomID = 4294967295`, even though it should display hit information for any `scale>0`

Note that this behavior is surprisingly identical when using `RTC_GEOMETRY_TYPE_DISC_POINT` geometry type.

Also, the norm of the ray direction is of importance, since `scale=1.75` and `dir[3] = {-0.5f, 0.f, 0.f}` yields a hit, whereas unit direction yields a miss.

As a matter of comparison, when creating the same example with triangles, the correct results is generated, e.g. :
```cpp
    RTCGeometry m_geometry = rtcNewGeometry(m_device, RTC_GEOMETRY_TYPE_TRIANGLE);
    float* point_vertices = (float*)rtcSetNewGeometryBuffer(m_geometry,RTC_BUFFER_TYPE_VERTEX, 0, RTC_FORMAT_FLOAT3, sizeof(float)*4, 3);
    point_vertices[0 ] =  0.0f;
    point_vertices[1 ] =  1.0f;
    point_vertices[2 ] =  0.0f;
    point_vertices[3 ] =  0.0f;
    point_vertices[4 ] =  0.0f;
    point_vertices[5 ] = -0.5f;
    point_vertices[6 ] =  0.707f;
    point_vertices[7 ] =  0.0f;
    point_vertices[8 ] =  0.0f;
    point_vertices[9 ] = -0.5f;
    point_vertices[10] = -0.707f;
    point_vertices[11] =  0.0f;
    uint* point_indices = (uint*)rtcSetNewGeometryBuffer(m_geometry,RTC_BUFFER_TYPE_INDEX, 0, RTC_FORMAT_UINT3, sizeof(uint)*3, 1);
    point_indices[0] = 0;
    point_indices[1] = 1;
    point_indices[2] = 2;
```

**Comment by UlysseV** [comment]
Another way to say this : intersection is missed when `dist(point.xyz, ray.org+ray.dir) < point.r`.

**Comment by svenwoop** [comment]
Thanks for reporting. Tag v3.5.1-alpha.0 fixes this issue.

**Comment by mathemaphysics** [comment]
I'm really confused because I'm running 3.8.0 and under no circumstance (using scale = 10.0 or scale = 3.0) does the correct result show up. I copied this and only this code into a file and built it. It compiles without complaint and fails 100% of the time to find the point.

I've spent hours banging my head against the wall. Is there a bug in later versions too?

**Comment by svenwoop** [comment]
In v3.5.1 an issue got fixed where the self intersection avoidance of ray oriented points did not work properly when ray direction was not normalized.
What you see here is expected behavior. Ray oriented discs are not real geometry, as their shape changes when ray orientation changes. Thus when you calculate a ray reflected from a ray oriented intersection, then you might hit the same ray oriented disc again. Therefore Embree drops ray oriented disc intersections that are 2*radius away of the ray origin. This factor 2 an get configured in CMake with EMBREE_CURVE_SELF_INTERSECTION_AVOIDANCE_FACTOR value. Just set this to 0 and you should see all intersections. However, you then likely need to do some intersection avoidance in your app.

**Comment by mathemaphysics** [comment]
@svenwoop Thanks for letting me know. I'm still trying to run the example at https://www.embree.org/api.html. Maybe this is the same problem issue.

My end application is just a simple ray-mesh intersection. I'm trying to get the intersection points for any triangle in the scene. Am I on the right track using these as examples (the API example shown above)?

**Comment by svenwoop** [comment]
Yes that example is a good starting point for ray/mesh intersection.

**Comment by mpups** [comment]
@mathemaphysics I guess you have figured this out by now but for anyone in future who has the same problem: many older examples you might come across do not work at all on newer versions of embree. E.g. in example above you have to additionally set the following field otherwise you get no hits:
```
ray.mask = -1;
```

They should really provide init functions for their structures!
