### ISSUE TITLE
Embree doesn't build in Debian on any architecture other than amd64

### ISSUE THREAD

**Issue by mfvescovi** [embree/embree#231]
See: https://buildd.debian.org/status/package.php?p=embree&suite=experimental

Is this expected? "-msse4.2" is clearly an optimization for x64 platforms, but is it really necessary?

**Comment by svenwoop** [comment]
We do not test Embree on 32bit Linux platforms. Please just create 64 bit packages. I do not believe that anybody seriously wants to work with 32bit rendering applications these days.

**Comment by alexmyczko** [comment]
It's not just about 32bit but also other 64bit platforms

**Comment by malaterre** [comment]
@svenwoop Your answer is a bit misleading, did you meant to say embree is x86_64 only because of the heavy use of intel intrinsics ? As I see it, you do not seems to support any of the following 64 bits arch (with somewhat equivalent intrinsics):

- ppc64(el)
- mips64(el)
- riscv64
- s390x
- sparc64

**Comment by cbenthin** [comment]
That is correct, Embree is only supported on the x86_64 architecture due to using x86 specific vector intrinsics.
