### ISSUE TITLE
find_embree tutorial fails with ispc

### ISSUE THREAD

**Issue by prideout** [embree/embree#239]
The ISPC declaration for this function looks like:

`RTCDevice rtcNewDevice(const uniform int8* uniform config);`

But the sole usage of this is in `find_embree_ispc.ispc`, which does not pass any arguments:

`RTCDevice device = rtcNewDevice();`

Also, it is unclear why there is no other occurrence of this function call in the ISPC tutorial code.

**Comment by cbenthin** [comment]
Thanks for pointing this out. In find_embree_ispc.ispc there indeed should be a rtcNewDevice(NULL) instead of a rtcNewDevice(). Will be fixed in the next release.
All tutorials (C++ and ISPC) share some general C++ code (tutorial.cpp) for initialization, command line parsing etc. This C++ code just calls the C-version of rtcNewDevice. 
For a pure ISPC application just use the ISPC version of rtcNewDevice.
