### ISSUE TITLE
Execution context for embree

### ISSUE THREAD

**Issue by stygianguest** [embree/embree#49]
We have stumbled on the unfortunate situation where two versions of embree are used within the same application (a plugin also uses embree). In that case the two versions of embree clash already at the instant that `rtcInit()` is called for the second time. We worked around this by renaming our dlls/so files, which is an ugly hack.

We would prefer to have a solution where embree provides an execution context and can thus be initialized multiple times.

**Comment by svenwoop** [comment]
One solution to this issue is to ignore the error code returned from the second rtcInit. However, this does only work properly if none of the libraries uses tries to configure some Embree internals through rtcInit. If that is the case, the configuration made by the first call is used.

The execution context appears to be a better solution for this issue. We will look into this.

**Comment by svenwoop** [comment]
We will add some device concept to the next release of Embree, which fixes this issue.
