### ISSUE TITLE
different results on avx2 vs avx(1) isa

### ISSUE THREAD

**Issue by stygianguest** [embree/embree#51]
During our testing we noticed that embree 2.6.1 (but also 2.5.0 before that) has different results on systems with avx2 support. Is this expected behavior? The differences may be small (didn't inspect in detail), but lead to large image differences especially in our photon maps with relatively large photons. For us this is, at the moment, sufficient reason to switch off avx2 entirely, which is a shame.

**Comment by svenwoop** [comment]
Yes this is expected behavior. The AVX2 codepath uses the FMA instruction to speed up some calculations. This obviously means that the results are not identical to the non-AVX2 codepath. U/V coordinates will be slightly different and a different triangle might be hit when hitting close to an edge.

However, both results are "correct" with regard to floating point accuracy. If you have a very sparse photon map with very large photons a little change at any place in your algorithm might place a big photon at a different location. This could be noticable and an error to expect from the sparse photon map approximation. 

Could you elaborate why this is a problem for your application? Why would the AVX2 user worry to get a different coarse lighting approximation than an AVX user?

**Comment by stygianguest** [comment]
What you describe is pretty much exactly what we observed. I think we will have to think of another solution to temporarily disable avx2 when testing and/or adapt the tests. 

thanks for the info!

-gideon
