### ISSUE TITLE
'__forceinline' does not name a type

### ISSUE THREAD

**Issue by cpgribble78** [embree/embree#90]
Hi,

I recently updated to Embree 2.10.0 (from 2.8.0), and I'm now getting the following error when compiling some Embree client programs:

  /usr/local/include/embree2/rtcore_ray.h:168:1: error: ‘__forceinline’ does not name a type

This error repeats for every line in 'embree2/rtcore_ray.h' that involves the '__forceinline' keyword.

The Embree library itself compiles and installs just fine; I've run a few of the included tutorial/test programs just fine as well.  I see this error when compiling a few client programs I have.

I am using g++5.2 on Ubuntu 15.04.  I understand that only GCC 4.8 is supported---but I get the same error when compiling clients with g++4.8 and g++4.9 as well.  (Note that the Embree library and included tutorial/test programs build just fine with g++5.2.)

Thanks,

Christiaan

**Comment by jeffamstutz** [comment]
Hi Christiaan,

It looks like this issue was fixed in the latest ```devel``` branch, so it will end up in the next Embree release. If you'd prefer to stay on Embree 2.10.0, a temporary workaround would be to:

```#define __forceinline inline```
```#include <rtcore_ray.h>```

 GCC 5.2 should otherwise work, please let us know if you run into any other build issues. Sorry for the inconvenience!

Jeff

**Comment by cpgribble78** [comment]
Fair enough, Jeff.  FWIW, to keep the semantics the same as in Visual Studio:

  #define __forceinline __attribute__((always_inline))

for GCC compilers.
